version: "3.7"

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data


  django-advanced:
    depends_on:
      - db
    container_name: django-advanced
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
